### model
model_name_or_path: /nas_data/userdata/randy/models/cxmt/pt/merge/cxmt-llama3.1-8b-cpt-v3

### method
stage: sft
do_train: true
finetuning_type: lora
lora_target: all
lora_rank: 512
lora_alpha: 1024
lora_dropout: 0.05
additional_target: embed_tokens,lm_head
flash_attn: fa2
deepspeed: examples/deepspeed/ds_z2_config.json

### dataset
dataset: semi-fineweb-alpaca-en-zh-shuffling,cxmt-cptest-sft
template: llama3
cutoff_len: 2048
overwrite_cache: true
preprocessing_num_workers: 64

### output
output_dir: /nas_data/userdata/randy/models/cxmt/sft/lora/cxmt-llama3.1-8b-pt-v3-sft-v3
overwrite_output_dir: true
logging_steps: 10
save_steps: 500
plot_loss: true

### train
per_device_train_batch_size: 4
gradient_accumulation_steps: 2
warmup_ratio: 0.1
learning_rate: 5e-6
num_train_epochs: 5.0
lr_scheduler_type: cosine
neftune_noise_alpha: 5
ddp_timeout: 180000000
bf16: true

### eval
per_device_eval_batch_size: 1
eval_strategy: steps
eval_steps: 100
val_size: 0.01
