### model
model_name_or_path: /nas_data/userdata/zhengwei/cxmt-models/base/cxmt-llama3.1-8b-cpt-v1

### method
stage: pt
do_train: true
finetuning_type: lora
lora_target: all
lora_rank: 16
lora_alpha: 32
lora_dropout: 0.1
flash_attn: fa2
deepspeed: examples/deepspeed/ds_z2_config.json

### dataset
dataset: cxmt-private,cxmt-lms-videos,cxmt-cptest
template: default
cutoff_len: 2048
overwrite_cache: true
preprocessing_num_workers: 64

### output
output_dir: /nas_data/userdata/randy/models/cxmt/pt/lora/cxmt-llama3.1-8b-pt-v4
overwrite_output_dir: true
logging_steps: 10
save_steps: 500
plot_loss: true

### train
per_device_train_batch_size: 4
gradient_accumulation_steps: 1
warmup_ratio: 0.1
learning_rate: 5e-5
num_train_epochs: 10.0
lr_scheduler_type: cosine
neftune_noise_alpha: 5
ddp_timeout: 180000000
bf16: true

### eval
per_device_eval_batch_size: 1
eval_strategy: steps
eval_steps: 500
val_size: 0.01
