### model
model_name_or_path: /nas_data/userdata/randy/models/Llama-3.1-8B-Instruct

### method
stage: pt
do_train: true
finetuning_type: lora
lora_target: all
lora_rank: 16
lora_alpha: 32
lora_dropout: 0.05
deepspeed: examples/deepspeed/ds_z2_config.json
flash_attn: fa2
use_dora: true

### dataset
dataset: semi-wechat,semikong-qa-15k-text,cxmt-dict,cxmt-cptest,cxmt-private,cxmt-lms-videos
template: default
cutoff_len: 2048
overwrite_cache: true
preprocessing_num_workers: 64

### output
output_dir: /nas_data/userdata/randy/models/cxmt/pt/lora/llama3.1-8b-instruct-pt-v2.1
overwrite_output_dir: true
logging_steps: 10
save_steps: 200
plot_loss: true
report_to: tensorboard

### train
per_device_train_batch_size: 4
gradient_accumulation_steps: 1
warmup_ratio: 0.1
learning_rate: 1e-4
num_train_epochs: 10.0
lr_scheduler_type: cosine
neftune_noise_alpha: 5
ddp_timeout: 180000000
bf16: true

### eval
per_device_eval_batch_size: 1
eval_strategy: steps
eval_steps: 100
val_size: 0.1
