### Note: DO NOT use quantized model or quantization_bit when merging lora adapters

### model
model_name_or_path: /nas_data/userdata/randy/models/Llama-3.1-8B-Instruct
adapter_name_or_path: /nas_data/userdata/randy/models/cxmt/pt/lora/llama3.1-8b-instruct-pt-v2.1
template: llama3
finetuning_type: lora

### export
export_dir: /nas_data/userdata/randy/models/cxmt/pt/merge/llama3.1-8b-instruct-pt-v2.1
export_size: 2
export_device: cpu
export_legacy_format: false
